### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by DyegoPimentel** [DyegoPimentel/Bot-Space-Crypto#1]
**Objetivo do projeto**
Ao final desde projeto, você terá o conhecimento necessário para criar os seus proprios projetos de automação utilizando Python, e terá a base necessária em Python para descobrir novas possibilidades de desenvolvimento de sistemas. 

---

- [x]  Visão geral e requisitos
- [x] Estrutura do projeto
- [x] O que é e como funciona uma função em Python
- [x] Transforme texto em voz
- [x] Loop utilizando range no python
- [x] Laço de repetição utilizando while no python
- [x] Verificações utilizando if no python
- [ ] Identificação de imagens no pyautogui
- [ ] Controle o mouse utilizando o pyautogui
- [ ] Controle o teclado utilizando o pyautogui
- [ ] Controle screenshots utilizando o pyautogui
- [ ] Criei um bot para jogar SpaceCrypto

---
